CREATE PROC FI_SP_ConsBeneficiarioV1
	@ID BIGINT
AS
BEGIN
	IF(ISNULL(@ID,0) = 0)
		SELECT NOME, ID, IDCLIENTE, CPF FROM BENEFICIARIO WITH(NOLOCK)
	ELSE
		SELECT NOME, CPF, IDCLIENTE, ID FROM BENEFICIARIO WITH(NOLOCK) WHERE ID = @ID
END